networks:
  pubel:

volumes:
  grafana_data:
  prometheus_data:
  loki_data:

services:
  grafana:
    image: grafana/grafana:12.2
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - pubel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docs/config/grafana/provisioning/dashboards:/var/lib/grafana/dashboards
      - ./docs/config/grafana/plugins:/var/lib/grafana/plugins
      - ./docs/config/grafana/provisioning:/etc/grafana/provisioning

  exporter:
    image: pubeldev/prusa_exporter:2.0.0-alpha3
    container_name: exporter
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./docs/config/prusa.yml
        target: /app/prusa.yml
    ports:
      - "10009:10009"
      - 8514:8514/udp
    command:
      - "--config.file=/app/prusa.yml"
      - "--log.level=info"
      - "--prusalink.scrape-timeout=5"
      - "--udp.ip-override=${HOST_IP}"
      - "--no-udp.gcode-enabled"
      - "--loki.push-url=http://loki:3100/loki/api/v1/push"
    depends_on:
      - prometheus
    networks:
      - pubel
 
  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./docs/config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - pubel

  loki:
    image: grafana/loki:3.5.5
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./docs/config/loki.yaml:/etc/loki/loki.yaml
      - loki_data:/loki
    networks:
      - pubel
